# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.28.2/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.28.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/guptaaryan16/Desktop/OSS/mlx_llm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/guptaaryan16/Desktop/OSS/mlx_llm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/Cellar/cmake/3.28.2/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.28.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/guptaaryan16/Desktop/OSS/mlx_llm/CMakeFiles /Users/guptaaryan16/Desktop/OSS/mlx_llm//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/guptaaryan16/Desktop/OSS/mlx_llm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mlx_nn

# Build rule for target.
mlx_nn: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mlx_nn
.PHONY : mlx_nn

# fast build rule for target.
mlx_nn/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlx_nn.dir/build.make CMakeFiles/mlx_nn.dir/build
.PHONY : mlx_nn/fast

#=============================================================================
# Target rules for targets named test_model

# Build rule for target.
test_model: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_model
.PHONY : test_model

# fast build rule for target.
test_model/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/test_model.dir/build.make examples/CMakeFiles/test_model.dir/build
.PHONY : test_model/fast

src/linear.o: src/linear.cpp.o
.PHONY : src/linear.o

# target to build an object file
src/linear.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlx_nn.dir/build.make CMakeFiles/mlx_nn.dir/src/linear.cpp.o
.PHONY : src/linear.cpp.o

src/linear.i: src/linear.cpp.i
.PHONY : src/linear.i

# target to preprocess a source file
src/linear.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlx_nn.dir/build.make CMakeFiles/mlx_nn.dir/src/linear.cpp.i
.PHONY : src/linear.cpp.i

src/linear.s: src/linear.cpp.s
.PHONY : src/linear.s

# target to generate assembly for a file
src/linear.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlx_nn.dir/build.make CMakeFiles/mlx_nn.dir/src/linear.cpp.s
.PHONY : src/linear.cpp.s

src/llama_model.o: src/llama_model.cpp.o
.PHONY : src/llama_model.o

# target to build an object file
src/llama_model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlx_nn.dir/build.make CMakeFiles/mlx_nn.dir/src/llama_model.cpp.o
.PHONY : src/llama_model.cpp.o

src/llama_model.i: src/llama_model.cpp.i
.PHONY : src/llama_model.i

# target to preprocess a source file
src/llama_model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlx_nn.dir/build.make CMakeFiles/mlx_nn.dir/src/llama_model.cpp.i
.PHONY : src/llama_model.cpp.i

src/llama_model.s: src/llama_model.cpp.s
.PHONY : src/llama_model.s

# target to generate assembly for a file
src/llama_model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlx_nn.dir/build.make CMakeFiles/mlx_nn.dir/src/llama_model.cpp.s
.PHONY : src/llama_model.cpp.s

src/module.o: src/module.cpp.o
.PHONY : src/module.o

# target to build an object file
src/module.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlx_nn.dir/build.make CMakeFiles/mlx_nn.dir/src/module.cpp.o
.PHONY : src/module.cpp.o

src/module.i: src/module.cpp.i
.PHONY : src/module.i

# target to preprocess a source file
src/module.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlx_nn.dir/build.make CMakeFiles/mlx_nn.dir/src/module.cpp.i
.PHONY : src/module.cpp.i

src/module.s: src/module.cpp.s
.PHONY : src/module.s

# target to generate assembly for a file
src/module.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlx_nn.dir/build.make CMakeFiles/mlx_nn.dir/src/module.cpp.s
.PHONY : src/module.cpp.s

src/utils.o: src/utils.cpp.o
.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlx_nn.dir/build.make CMakeFiles/mlx_nn.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlx_nn.dir/build.make CMakeFiles/mlx_nn.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mlx_nn.dir/build.make CMakeFiles/mlx_nn.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... mlx_nn"
	@echo "... test_model"
	@echo "... src/linear.o"
	@echo "... src/linear.i"
	@echo "... src/linear.s"
	@echo "... src/llama_model.o"
	@echo "... src/llama_model.i"
	@echo "... src/llama_model.s"
	@echo "... src/module.o"
	@echo "... src/module.i"
	@echo "... src/module.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

